services:
  django:
    build:
      context: ./backend/coffeeshop
    env_file: ./backend/coffeeshop/.env
    volumes:
      - ./backend/coffeeshop:/app  # Fixed volume mapping
    ports:
      - "8000:8000"

  nextjs:
    build:
      context: ./frontend
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - django
    command: >
      sh -c "npm install && npm run build && npm run start"
